### ISSUE TITLE
`.AppImage` for Linux

### ISSUE THREAD

**Issue by imalightbulb** [LiamRiddell/NoteMaster#3]
Please provide an `.AppImage` package for Linux users, can't wait to try it out!

**Comment by LiamRiddell** [comment]
Hi @JackQAQ-byte, Thanks for reaching out! I'll look into it. Side note; Linux is currently untested.. here be dragons 🐉

**Comment by LiamRiddell** [comment]
@JackQAQ-byte - [NoteMaster v0.2.3](https://github.com/LiamRiddell/NoteMaster/releases/tag/v0.2.3) now has Linux and OS X distributions. Thank you for supporting NoteMaster.
